TIEB/TIEB/Models/IncomeType.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomeType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IncomeType()
        {
            this.Income = new HashSet<Income>();
        }
    
        public int IncomeTypeID { get; set; }
        public string IncomeName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Income> Income { get; set; }
    }
}

TIEB/TIEB/Controllers/IncomesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TIEB.MainController;
using TIEB.Models;
using PagedList;

namespace TIEB.Controllers
{
    // Ana bir controller tarafından inherit edilmiştir giriş yapılınca devreye girer
    public class IncomesController : BaseController
    {
        private TIEB_BudgetDBEntities db = new TIEB_BudgetDBEntities();

        //Incomes/Index Gelirlerin listelendiği sayfadır Search ve Sort işlemlerini de bu Method yapar.
        public ActionResult Index(string SearchString1, string SearchString2, string date1, string date2, string amount1, string amount2,
            string Sorting_Order, string sortOrder,string currentFilter, string currentFilter1, string currentFilter2, int? page)
        {
            ViewBag.SortingAmount = String.IsNullOrEmpty(Sorting_Order) ? "Amount" : "";
            ViewBag.SortingDate = String.IsNullOrEmpty(Sorting_Order) ? "Date" : "";
            ViewBag.SortingIncomeName = String.IsNullOrEmpty(Sorting_Order) ? "IncomeName" : "";
            ViewBag.SortingExplanation = String.IsNullOrEmpty(Sorting_Order) ? "Explanation" : "";

            var name = Session["UserName"] as Persons;
            if (name == null) { return View(); }

            if (Sorting_Order == null)
                Sorting_Order = sortOrder;
            ViewBag.CurrentSort = Sorting_Order;

            int pageSize = 10;
            int pageNumber = (page ?? 1);

            if (SearchString1 != null || SearchString2 != null || date1 != null || date2 != null || amount1 != null || amount2 != null)
            {
                page = 1;
                
                TempData["temp1"] = date1;
                TempData.Keep();
                TempData["temp2"] = date2;
                TempData.Keep();
                TempData["temp3"] = amount1;
                TempData.Keep();
                TempData["temp4"] = amount2;
                TempData.Keep();
                TempData["SearchString1"] = SearchString1;
                TempData.Keep();
                TempData["SearchString2"] = SearchString2;
                TempData.Keep();
            }
            else
            {
                string temp1 = "", temp2 = "", temp3 = "", temp4 = "";
                string tempSearchString1 = "", tempSearchString2 = "";


                temp1 = Convert.ToString(TempData["temp1"]);
                TempData.Keep();
                temp2 = Convert.ToString(TempData["temp2"]);
                TempData.Keep();
                temp3 = Convert.ToString(TempData["temp3"]);
                TempData.Keep();
                temp4 = Convert.ToString(TempData["temp4"]);
                TempData.Keep();
                tempSearchString1 = Convert.ToString(TempData["SearchString1"]);
                TempData.Keep();
                tempSearchString2 = Convert.ToString(TempData["SearchString2"]);
                TempData.Keep();

                
                

                if (temp1 != "")
                    date1 = currentFilter1;
                if (temp2 != "")
                    date2 = currentFilter2;
                if (temp3 != "")
                    amount1 = currentFilter1;
                if (temp4 != "")
                    amount2 = currentFilter2;
                if(tempSearchString1 != "")
                    SearchString1 = currentFilter;
                if (tempSearchString2 != "")
                    SearchString2 = currentFilter;
            }

            var income = from inc in db.Income select inc;

            switch (Sorting_Order)
            {
                case "Amount":
                    income = income.OrderBy(x => x.Amount).Where(x => x.PersonID == name.PersonID); 
                    break;
                case "Date":
                    income = income.OrderBy(x => x.Date).Where(x => x.PersonID == name.PersonID); 
                    break;
                case "IncomeName":
                    income = (from i in db.Income
                              join it in db.IncomeType on i.IncomeType equals it.IncomeTypeID
                              where i.PersonID == name.PersonID
                              orderby it.IncomeName
                              select i);
                    break;
                case "Explanation":
                    income = income.OrderBy(e => e.Explanation).Where(x => x.Explanation != null && x.PersonID == name.PersonID); 
                    break;
                default:
                    income = income.OrderBy(x => x.IncomeID).Where(x => x.PersonID == name.PersonID); 
                    break;

            }
            
            if (!String.IsNullOrEmpty(SearchString1))
            {
                
                ViewBag.CurrentFilter = SearchString1;
                income = (from i in db.Income
                               join it in db.IncomeType on i.IncomeType equals it.IncomeTypeID
                               where it.IncomeName.Contains(SearchString1) && i.PersonID == name.PersonID
                               orderby i.IncomeID
                               select i);
            }
            else if (!String.IsNullOrEmpty(SearchString2))
            {
                ViewBag.CurrentFilter = SearchString2;
                income = income.Where(x => x.Explanation.Contains(SearchString2)
                && x.PersonID == name.PersonID).OrderBy(x => x.IncomeID);
            }
            else if (!String.IsNullOrEmpty(date1) && !String.IsNullOrEmpty(date2))
            {
                ViewBag.CurrentFilter1 = date1;
                ViewBag.CurrentFilter2 = date2;
                DateTime d1 = Convert.ToDateTime(date1);
                DateTime d2 = Convert.ToDateTime(date2);
                income = income.Where(x => x.Date >= d1 && x.Date <= d2
                && x.PersonID == name.PersonID).OrderBy(x => x.IncomeID);
            }
            else if (!String.IsNullOrEmpty(date1))
            {
                ViewBag.CurrentFilter1 = date1;
                DateTime d1 = Convert.ToDateTime(date1);
                income = income.Where(x => x.Date >= d1
                && x.PersonID == name.PersonID).OrderBy(x => x.IncomeID);
            }
            else if (!String.IsNullOrEmpty(date2))
            {
                ViewBag.CurrentFilter2 = date2;
                DateTime d2 = Convert.ToDateTime(date2);
                income = income.Where(x => x.Date <= d2
                && x.PersonID == name.PersonID).OrderBy(x => x.IncomeID);
            }

            else if (!String.IsNullOrEmpty(amount1) && !String.IsNullOrEmpty(amount2))
            {
                ViewBag.CurrentFilter1 = amount1;
                ViewBag.CurrentFilter2 = amount2;
                decimal a1 = Convert.ToDecimal(amount1);
                decimal a2 = Convert.ToDecimal(amount2);
                income = income.Where(x => x.Amount >= a1 && x.Amount <= a2
                && x.PersonID == name.PersonID).OrderBy(x => x.IncomeID);
            }
            else if (!String.IsNullOrEmpty(amount1))
            {
                ViewBag.CurrentFilter1 = amount1;
                decimal a1 = Convert.ToDecimal(amount1);
                income = income.Where(x => x.Amount >= a1
                && x.PersonID == name.PersonID).OrderBy(x => x.IncomeID);
            }
            else if (!String.IsNullOrEmpty(date2))
            {
                ViewBag.CurrentFilter2 = amount2;
                decimal a2 = Convert.ToDecimal(amount2);
                income = income.Where(x => x.Amount <= a2
                && x.PersonID == name.PersonID).OrderBy(x => x.IncomeID);
            }

            Total(income);
            ViewBag.HtmlStr = income.Count();
            return View(income.ToPagedList(pageNumber, pageSize));
        }

        // GET: Incomes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Income income = db.Income.Find(id);
            if (income == null)
            {
                return HttpNotFound();
            }
            return View(income);
        }

        // GET: Incomes/Create
        public ActionResult Create()
        {
            ViewBag.IncomeType = new SelectList(db.IncomeType, "IncomeTypeID", "IncomeName");
            ViewBag.PersonID = new SelectList(db.Persons, "PersonID", "Name");
            return View();
        }

        // POST: Incomes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IncomeID,PersonID,IncomeType,Amount,Date,Explanation")] Income income)
        {
            if (ModelState.IsValid)
            {
                
                db.Income.Add(income);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IncomeType = new SelectList(db.IncomeType, "IncomeTypeID", "IncomeName", income.IncomeType);
            ViewBag.PersonID = new SelectList(db.Persons, "PersonID", "Name", income.PersonID);
            return View(income);
        }

        [HttpPost]
        public JsonResult IncomeTypeOther(int id)
        {
            var returnRsult = new ReturnResult();
            foreach (var item in db.IncomeType.Where(e => e.IncomeTypeID == id))
            {
                if (item.IncomeName == "DİĞER")
                {
                    returnRsult.Message = "AppearTextBox";
                }
                
                
            }
            return Json(returnRsult, JsonRequestBehavior.AllowGet);
        }

        // GET: Incomes/Edit/5

TIEB/TIEB/Views/Incomes/Create.cshtml
@model TIEB.Models.Income
@using TIEB.Models;
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<head>
    @*div bloklarını yan yana koymak için css*@
    <style type="text/css">
        .column {
            float: left;
            width: 560px;
        }
    </style>
</head>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal column">
        <h4>Gelir Ekleme Sayfası</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @{
            var name = Session["UserName"] as Persons;
            if (name == null) { return; } @*Kullanıcı girşi ile Sessiona kaydedilen kullanıcı adı kontrolü boş mu dolu mu?*@
        }
        <div class="form-group" hidden>
            @Html.LabelFor(model => model.PersonID, "PersonID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("PersonID", name.PersonID, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PersonID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IncomeType, "Gelir Türü", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IncomeType", null,"--- Seçiniz ---", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IncomeType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </div>
        <div>
            @Html.ActionLink("Listeye Geri Dön", "Index")
        </div>
    </div>

    <div class="form-horizontal column" id="form-ExpTextBox" hidden>
        <h4>Listede Olmayan Gelir Türü Giriniz</h4>
        <hr />
        <div class="col-md-10">
            @Html.EditorFor(model => model.Explanation, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Explanation, "", new { @class = "text-danger" })
        </div>
    </div>
 }

@section scripts
{
    <script type="text/javascript">
        $(document).ready(function () {
            $("#IncomeType").change(function () { // IncomeType nesnesi seçildiğinde
                var id = $(this).val();
                $.ajax({
                    url: '/Incomes/IncomeTypeOther',
                    type: 'POST',
                    dataType: 'json',
                    data: { 'id': id }, // IncomeType Methodunun parametresine id değeri Json olarak gönderilir
                    success: function (data) {
                        // Json olarak geri dönen değer başarılıysa if yapısıyla kontrol edilir
                        // Hangi nesnelerin görünüp görünmeyeceği belirlenir
                        if (data.Message == "AppearTextBox") {
                            $("#form-ExpTextBox").show();
                        }
                        else {
                            $("#form-ExpTextBox").hide();
                        }
                    }
                });
            });
        });
</script>
}

TIEB/TIEB/Views/Incomes/Delete.cshtml
@model TIEB.Models.Income

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Silme Sayfası</h2>

<h3>Bu Kaydı Silmek İstediğinizden Emin Misiniz?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Gelir Türü")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IncomeType1.IncomeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Explanation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Explanation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Persons.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Persons.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Sil" class="btn btn-default" /> |
            @Html.ActionLink("Listeye Geri Dön", "Index")
        </div>
    }
</div>

TIEB/TIEB/Views/Incomes/Details.cshtml
@model TIEB.Models.Income

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detay Sayfası</h2>

<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Gelir Türü")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IncomeType1.IncomeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Explanation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Explanation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Persons.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Persons.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Düzenle", "Edit", new { id = Model.IncomeID }) |
    @Html.ActionLink("Listeye Geri Dön", "Index")
</p>

TIEB/TIEB/Views/Incomes/Edit.cshtml
@model TIEB.Models.Income
@using TIEB.Models;
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Düzenleme Sayfası</h2>
<head>
    @*div bloklarını yan yana koymak için css*@
    <style type="text/css">
        .column {
            float: left;
            width: 560px;
        }
    </style>
</head>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal column" id="form-EditList">
        <h4>Gelir Düzenleme Sayfası</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @{
            var name = Session["UserName"] as Persons;
            if (name == null) { return; } @*Kullanıcı girşi ile Sessiona kaydedilen kullanıcı adı kontrolü boş mu dolu mu?*@
        }
        @Html.HiddenFor(model => model.IncomeID)

        <div class="form-group">
            @Html.LabelFor(model => model.PersonID, "PersonID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PersonID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PersonID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IncomeType, "IncomeType", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IncomeType", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IncomeType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Değiştir" class="btn btn-default" />
            </div>
        </div>
        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
    <div class="form-horizontal column" id="form-ExpTextBox" hidden>
        <h4>Listede Olmayan Gelir Türü Giriniz</h4>
        <hr />
        <div class="col-md-10">
            @Html.EditorFor(model => model.Explanation, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Explanation, "", new { @class = "text-danger" })
        </div>
    </div>
}
@section scripts
{
    <script type="text/javascript">
        $(document).ready(function () {
            $("#IncomeType").text(function () { // IncomeType nesnesi sayfa açıldığında texti doluysa 
                var id = $(this).val();
                $.ajax({
                    url: '/Incomes/IncomeTypeOther',
                    type: 'POST',
                    dataType: 'json',
                    data: { 'id': id }, // IncomeType Methodunun parametresine id değeri Json olarak gönderilir
                    success: function (data) {
                        // Json olarak geri dönen değer başarılıysa if yapısıyla kontrol edilir
                        // Hangi nesnelerin görünüp görünmeyeceği belirlenir
                        if (data.Message == "AppearTextBox") {
                            $("#form-ExpTextBox").show();
                        }
                        else {
                            $("#form-ExpTextBox").hide();
                            $('input#Explanation').val('');
                        }

                    }
                });
            });

            /********************************************************************************************************/

            $("#IncomeType").change(function () { // IncomeType nesnesi seçildiğinde
                var id = $(this).val();
                $.ajax({
                    url: '/Incomes/IncomeTypeOther',
                    type: 'POST',
                    dataType: 'json',
                    data: { 'id': id }, // IncomeType Methodunun parametresine id değeri Json olarak gönderilir
                    success: function (data) {
                        // Json olarak geri dönen değer başarılıysa if yapısıyla kontrol edilir
                        // Hangi nesnelerin görünüp görünmeyeceği belirlenir
                        if (data.Message == "AppearTextBox") {
                            $("#form-ExpTextBox").show();
                        }
                        else {
                            $("#form-ExpTextBox").hide();
                            $('input#Explanation').val('');
                        }

                    }
                });
            });
        });
    </script>
}

TIEB/TIEB/Views/Incomes/Index.cshtml
@*@model IEnumerable<TIEB.Models.Income>*@
@model PagedList.IPagedList<TIEB.Models.Income>
@using TIEB.Models;
@using PagedList.Mvc;

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>GELİRLERİM</h2>
<head>
    <style type="text/css">
        .column {
            float: left;
            width: 250px;
            
        }
    </style>
</head>

<p>
    @Html.ActionLink("Gelir Ekle", "Create")
</p>

<div class="form-group pull-right">

    @Html.Label("Arama Kriteri", htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.DropDownList("searchType", new List<SelectListItem>
                {
                    new SelectListItem{ Text="Gelir Türüne Göre Arama", Value="IncomeNameSearch"},
                    new SelectListItem{ Text="Miktara Göre Arama", Value="AmountSearch"},
                    new SelectListItem{ Text="Tarihe Göre Arama", Value="DateSearch"},
                    new SelectListItem{ Text="Diğer Gelir Türüne Göre Arama", Value="OtherIncomeNameSearch"}
                }, "--- Seçiniz ---", new { @class = "form-control" })
        @Html.ValidationMessage("searchType", "", new { @class = "text-danger" })
    </div>
</div>
<br /><br /><br />
<p class="pull-left column">
    @Html.ActionLink("Listeyi Yenile", "Index")
</p>
<p class="column">
    Toplam : @ViewBag.TOTAL
</p>


@using (Html.BeginForm())
{

    <div class="pull-right" id="form-search1" hidden>
        <b>Gelir Türüne Göre Arama Yap:</b>
        @Html.TextBox("SearchString1", ViewBag.CurrentFilter as string)
        <input type="submit" value="Arama Yap" id="search" />
    </div>
    <div class="pull-right" id="form-search2" hidden>
        <b>Diğer Gelir Türüne Göre Arama Yap:</b>
        @Html.TextBox("SearchString2", ViewBag.CurrentFilter as string)
        <input type="submit" value="Arama Yap" id="search" />
    </div>
    <div class="pull-right" id="form-between-date" hidden>
        <b>İki Tarih Arası Arama:</b>
        @Html.TextBox("date1", ViewBag.CurrentFilter1 as string)
        @Html.TextBox("date2", ViewBag.CurrentFilter2 as string)
        <input type="submit" value="Arama Yap" id="search" />
    </div>
    <div class="pull-right" id="form-between-amount" hidden>
        <b>Miktarlar Arası Arama:</b>
        @Html.TextBox("amount1", ViewBag.CurrentFilter1 as string)
        @Html.TextBox("amount2", ViewBag.CurrentFilter2 as string)
        <input type="submit" value="Arama Yap" id="search" />
    </div>
}
<br /><br /><br />



@using (Html.BeginForm("Index", "Incomes", FormMethod.Post))
{
    <table class="table" style="text-align:center">
        <tr>
            <th style="text-align:center">
                @Html.ActionLink("Gelir Türü", "Index", new { Sorting_Order = ViewBag.SortingIncomeName, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th style="text-align:center">
                @Html.ActionLink("Miktar", "Index", new { Sorting_Order = ViewBag.SortingAmount, currentFilter1 = ViewBag.CurrentFilter1, currentFilter2 = ViewBag.CurrentFilter2 })
            </th>
            <th style="text-align:center">
                @Html.ActionLink("Tarih", "Index", new { Sorting_Order = ViewBag.SortingDate, currentFilter1 = ViewBag.CurrentFilter1, currentFilter2 = ViewBag.CurrentFilter2 })
            </th>
            <th style="text-align:center">
                @Html.ActionLink("Diğer Gelir Türü", "Index", new { Sorting_Order = ViewBag.SortingExplanation, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th></th>
        </tr>
        @{
            var name = Session["UserName"] as Persons;
            if (name == null){return;}
        }
        

        @foreach (var item in Model.Where(x => x.PersonID == name.PersonID))
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.IncomeType1.IncomeName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Amount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Explanation)
                </td>
                <td>
                    @Html.ActionLink("Düzenle", "Edit", new { id = item.IncomeID }) |
                    @Html.ActionLink("Detay", "Details", new { id = item.IncomeID }) |
                    @Html.ActionLink("Sil", "Delete", new { id = item.IncomeID })
                </td>
            </tr>
        }

    </table>
}

<br /><br />
@(Html.Raw(ViewBag.HtmlStr)) sonuç
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, currentFilter1 = ViewBag.CurrentFilter1, currentFilter2 = ViewBag.CurrentFilter2 }))



@section scripts
{
    <script type="text/javascript">
        $(document).ready(function () {
            $("#form-search").hide();
            $("#form-between-date").hide();
            $("#form-between-amount").hide();
            $("#searchType").change(function () {
                    var value = $(this).val();
                    $.ajax({
                        url: '/Incomes/SearchType',
                        type: 'POST',
                        dataType: 'json',
                        data: { 'value': value },
                        success: function (data) {

                            if (data.Message == "AppearIncomeName")
                            {
                                $("#form-search1").show();
                                $("#form-search2").hide();
                                $("#form-between-date").hide();
                                $("#form-between-amount").hide();


                            }
                            else if (data.Message == "AppearAmount")
                            {
                                $("#form-search1").hide();
                                $("#form-search2").hide();
                                $("#form-between-date").hide();
                                $("#form-between-amount").show();

                            }
                            else if (data.Message == "AppearDate")
                            {
                                $("#form-search1").hide();
                                $("#form-search2").hide();
                                $("#form-between-date").show();
                                $("#form-between-amount").hide();

                            }
                            else if (data.Message == "AppearOtherIncomeName") {
                                $("#form-search1").hide();
                                $("#form-search2").show();
                                $("#form-between-date").hide();
                                $("#form-between-amount").hide();


                            }
                        }

                    });
                });
            });
    </script>
}