TIEB/TIEB/Controllers/CreditCartTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TIEB.MainController;
using TIEB.Models;

namespace TIEB.Controllers
{
    // Ana bir controller tarafından inherit edilmiştir giriş yapılınca devreye girer
    public class CreditCartTypesController : BaseController
    {
        private TIEB_BudgetDBEntities db = new TIEB_BudgetDBEntities();

        // GET: CreditCartTypes
        // CreditCartType tablosundaki verileri PersonID ye göre listeler
        public ActionResult Index()
        {
            var creditCartType = db.CreditCartType.Include(c => c.Persons);
            return View(creditCartType.ToList());
        }

        // GET: CreditCartTypes/Details/5
        // Belirtilen id değerine uygun kişinin Kredi kartı bilgilerini getirir
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CreditCartType creditCartType = db.CreditCartType.Find(id);
            if (creditCartType == null)
            {
                return HttpNotFound();
            }
            return View(creditCartType);
        }

        // GET: CreditCartTypes/Create
        public ActionResult Create()
        {
            ViewBag.PersonID = new SelectList(db.Persons, "PersonID", "Name");
            return View();
        }

        // POST: CreditCartTypes/Create
        // View/Create üzerinden Post edilen verileri alır ve Databaseye kaydeder
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CreditCartID,PersonID,CreditCartName")] CreditCartType creditCartType)
        {
            if (ModelState.IsValid)
            {
                db.CreditCartType.Add(creditCartType);
                db.SaveChanges();
                return RedirectToAction("Create"); // Veri kaydedildikten sonra tekrardan Create ekranına yönlendirir.
            }

            ViewBag.PersonID = new SelectList(db.Persons, "PersonID", "Name", creditCartType.PersonID);
            return View(creditCartType);
        }

        // GET: CreditCartTypes/Edit/5
        // Belirtilen id ile kişinin Database deki Kredi kartı bilgilerini Edit ekranındaki nesnelere doldurur
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CreditCartType creditCartType = db.CreditCartType.Find(id);
            if (creditCartType == null)
            {
                return HttpNotFound();
            }
            ViewBag.PersonID = new SelectList(db.Persons, "PersonID", "Name", creditCartType.PersonID);
            return View(creditCartType);
        }

        // POST: CreditCartTypes/Edit/5
        // View/CreditCartTypes/Crate üzerinden Post edilen bilgileri Database üzerine tekrardan kaydeder yani değiştirir
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CreditCartID,PersonID,CreditCartName")] CreditCartType creditCartType)
        {
            if (ModelState.IsValid)
            {
                db.Entry(creditCartType).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PersonID = new SelectList(db.Persons, "PersonID", "Name", creditCartType.PersonID);
            return View(creditCartType);
        }

        // GET: CreditCartTypes/Delete/5
        // id si belli olan veriyi View/CreditCartTypes/Delete ekranına gösterir ve silip silmeyeceğini sorar
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CreditCartType creditCartType = db.CreditCartType.Find(id);
            if (creditCartType == null)
            {
                return HttpNotFound();
            }
            return View(creditCartType);
        }

        // POST: CreditCartTypes/Delete/5
        // View/CreditCartTypes/Delete ekranında sil butonuna basılıp Post edilen bilgi id si ile Database den silinir
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CreditCartType creditCartType = db.CreditCartType.Find(id);
            db.CreditCartType.Remove(creditCartType);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        // Dispose methodu ile Database bağlantısı kesilir ve Bellekte şişmeler engellenir
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TIEB/TIEB/Controllers/PersonsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TIEB.Models;

namespace TIEB.Controllers
{
    public class PersonsController : Controller
    {
        private TIEB_BudgetDBEntities db = new TIEB_BudgetDBEntities();

        // GET: Persons
        public ActionResult Index()
        {
            return View();
        }
        // Persons tablosundaki verileri PersonID ye göre listeler ayrıca giriş yapılan kişinin profilini gösterir
        public ActionResult List()
        {
            var persons = db.Persons.Include(p => p.BankCartType).Include(p => p.CreditCartType).Include(p => p.Expense).Include(p => p.Income);
            return View(persons.ToList());
        }

        // GET: Persons/Details/5
        // Belirtilen id değerine uygun kişinin Banka bilgilerini getirir
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Persons persons = db.Persons.Find(id);
            if (persons == null)
            {
                return HttpNotFound();
            }
            return View(persons);
        }

        // GET: Persons/Create
        public ActionResult Create()
        {
            ViewBag.PersonID = new SelectList(db.BankCartType, "BankCartID", "BankCartName");
            ViewBag.PersonID = new SelectList(db.CreditCartType, "CreditCartID", "CreditCartName");
            ViewBag.PersonID = new SelectList(db.Expense, "ExpenseID", "ExpenseID");
            ViewBag.PersonID = new SelectList(db.Income, "IncomeID", "IncomeID");
            return View();
        }

        // POST: Persons/Create
        // View/Persons/Create üzerinden Post edilen verileri alır ve Databaseye kaydeder
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PersonID,Name,SurName,UserName,Password,Email,Gender,BrithDate")] Persons persons)
        {
            if (ModelState.IsValid)
            {
                foreach (var item in db.Persons)
                {
                    if (persons.UserName == item.UserName) // Kişi eklerken Kullanıcı adı eğer Database de mevcutsa hata verir 
                    {
                        ViewBag.HATA = "Bu Kullanıcı Adı Daha Önceden Alınmış";
                        return View("Create");
                    }
                    if (persons.Email == item.Email) // Kişi eklerken mail adresi eğer Database de mevcutsa hata verir
                    {
                        ViewBag.HATA = "Bu Mail Adresi Daha Önceden Alınmış";
                        return View("Create");
                    }
                }
                db.Persons.Add(persons);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PersonID = new SelectList(db.BankCartType, "BankCartID", "BankCartName", persons.PersonID);
            ViewBag.PersonID = new SelectList(db.CreditCartType, "CreditCartID", "CreditCartName", persons.PersonID);
            ViewBag.PersonID = new SelectList(db.Expense, "ExpenseID", "ExpenseID", persons.PersonID);
            ViewBag.PersonID = new SelectList(db.Income, "IncomeID", "IncomeID", persons.PersonID);
            return View(persons);
        }

        // GET: Persons/Edit/5
        // Belirtilen id ile kişinin Database deki Banka bilgilerini Edit ekranındaki nesnelere doldurur
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Persons persons = db.Persons.Find(id);
            if (persons == null)
            {
                return HttpNotFound();
            }
            ViewBag.PersonID = new SelectList(db.BankCartType, "BankCartID", "BankCartName", persons.PersonID);
            ViewBag.PersonID = new SelectList(db.CreditCartType, "CreditCartID", "CreditCartName", persons.PersonID);
            ViewBag.PersonID = new SelectList(db.Expense, "ExpenseID", "ExpenseID", persons.PersonID);
            ViewBag.PersonID = new SelectList(db.Income, "IncomeID", "IncomeID", persons.PersonID);
            return View(persons);
        }

        // POST: Persons/Edit/5
        // View/Persons/Edit üzerinden Post edilen bilgileri Database üzerine tekrardan kaydeder yani değiştirir
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PersonID,Name,SurName,UserName,Password,Email,Gender,BrithDate")] Persons persons)
        {
            if (ModelState.IsValid)
            {
                db.Entry(persons).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PersonID = new SelectList(db.BankCartType, "BankCartID", "BankCartName", persons.PersonID);
            ViewBag.PersonID = new SelectList(db.CreditCartType, "CreditCartID", "CreditCartName", persons.PersonID);
            ViewBag.PersonID = new SelectList(db.Expense, "ExpenseID", "ExpenseID", persons.PersonID);
            ViewBag.PersonID = new SelectList(db.Income, "IncomeID", "IncomeID", persons.PersonID);
            return View(persons);
        }

        // GET: Persons/Delete/5
        // id si belli olan veriyi View/BankCartTypes/Delete ekranına gösterir ve silip silmeyeceğini sorar
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Persons persons = db.Persons.Find(id);
            if (persons == null)
            {
                return HttpNotFound();
            }
            return View(persons);
        }

        // POST: Persons/Delete/5
        // View/Persons/Delete ekranında sil butonuna basılıp Post edilen bilgi id si ile Database den silinir
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Persons persons = db.Persons.Find(id);
            db.Persons.Remove(persons);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // Dispose methodu ile Database bağlantısı kesilir ve Bellekte şişmeler engellenir
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        


    }
}

TIEB/TIEB/Views/CreditCartTypes/Create.cshtml
@model TIEB.Models.CreditCartType
@using TIEB.Models;
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Kredi Kartı Ekleme Sayfası</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @{
            var name = Session["UserName"] as Persons;
            if (name == null){return;} @*Kullanıcı girşi ile Sessiona kaydedilen kullanıcı adı kontrolü boş mu dolu mu?*@
        }
        <div class="form-group" hidden>
            @Html.LabelFor(model => model.PersonID, "PersonID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("PersonID", name.PersonID, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PersonID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreditCartName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreditCartName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreditCartName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Profilime Geri Dön ", "List", "Persons") |
    @Html.ActionLink("Tüm Kredi Kartı Listem ", "Index")
</div>

TIEB/TIEB/Views/CreditCartTypes/Delete.cshtml
@model TIEB.Models.CreditCartType

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Silme Sayfası</h2>

<h3>Bu Kaydı Silmek İstediğinizden Emin Misiniz?</h3>
<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CreditCartName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreditCartName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Persons.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Persons.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Sil" class="btn btn-default" /> |
            @Html.ActionLink("Kredi Kartı Listeme Geri Dön", "Index")
        </div>
    }
</div>

TIEB/TIEB/Views/CreditCartTypes/Details.cshtml
@model TIEB.Models.CreditCartType

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detay Sayfası</h2>

<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CreditCartName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreditCartName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Persons.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Persons.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Düzenle", "Edit", new { id = Model.CreditCartID }) |
    @Html.ActionLink("Kredi Kartı Listeme Geri Dön", "Index")
</p>

TIEB/TIEB/Views/CreditCartTypes/Edit.cshtml
@model TIEB.Models.CreditCartType

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Düzenleme Sayfası</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CreditCartID)

        <div class="form-group" hidden>
            @Html.LabelFor(model => model.PersonID, "PersonID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PersonID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PersonID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreditCartName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreditCartName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreditCartName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Değiştir" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Kredi Kartı Listeme Geri Dön", "Index")
</div>

TIEB/TIEB/Views/CreditCartTypes/Index.cshtml
@model IEnumerable<TIEB.Models.CreditCartType>
@using TIEB.Models;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Kredi Kartlarım</h2>

<p>
    @Html.ActionLink("Kredi Kartlarım", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CreditCartName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Persons.Name)
        </th>
        <th></th>
    </tr>

@{
    var name = Session["UserName"] as Persons;
    if (name == null) { return; }
}
@foreach (var item in Model.Where(x => x.PersonID == name.PersonID))
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CreditCartName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Persons.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.CreditCartID }) |
            @Html.ActionLink("Details", "Details", new { id=item.CreditCartID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.CreditCartID })
        </td>
    </tr>
}

</table>
<br /><br />
<div>
    @Html.ActionLink("Profilime Geri Dön ", "List", "Persons")
</div>