TIEB/TIEB/Controllers/BankCartTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TIEB.MainController;
using TIEB.Models;

namespace TIEB.Controllers
{
    // Ana bir controller tarafından inherit edilmiştir giriş yapılınca devreye girer
    public class BankCartTypesController : BaseController  
    {
        private TIEB_BudgetDBEntities db = new TIEB_BudgetDBEntities(); 

        // GET: BankCartTypes
        // BankCartType tablosundaki verileri PersonID ye göre listeler
        public ActionResult Index()
        {
            var bankCartType = db.BankCartType.Include(b => b.Persons); 
            return View(bankCartType.ToList());
        }

        // GET: BankCartTypes/Details/5
        // Belirtilen id değerine uygun kişinin Banka bilgilerini getirir
        public ActionResult Details(int? id) 
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BankCartType bankCartType = db.BankCartType.Find(id);
            if (bankCartType == null)
            {
                return HttpNotFound();
            }
            return View(bankCartType);
        }

        // GET: BankCartTypes/Create
        public ActionResult Create()
        {
            ViewBag.PersonID = new SelectList(db.Persons, "PersonID", "Name");
            return View();
        }

        // POST: BankCartTypes/Create
        // View/BankCartTypes/Create üzerinden Post edilen verileri alır ve Databaseye kaydeder
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BankCartID,PersonID,BankCartName")] BankCartType bankCartType)
        {
            if (ModelState.IsValid)
            {
                db.BankCartType.Add(bankCartType);
                db.SaveChanges();
                return RedirectToAction("Create"); // Veri kaydedildikten sonra tekrardan Create ekranına yönlendirir.
            }

            ViewBag.PersonID = new SelectList(db.Persons, "PersonID", "Name", bankCartType.PersonID);
            return View(bankCartType);
        }

        // GET: BankCartTypes/Edit/5
        // Belirtilen id ile kişinin Database deki Banka bilgilerini Edit ekranındaki nesnelere doldurur
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BankCartType bankCartType = db.BankCartType.Find(id);
            if (bankCartType == null)
            {
                return HttpNotFound();
            }
            ViewBag.PersonID = new SelectList(db.Persons, "PersonID", "Name", bankCartType.PersonID);
            return View(bankCartType);
        }

        // POST: BankCartTypes/Edit/5
        // View/BankCartType/Crate üzerinden Post edilen bilgileri Database üzerine tekrardan kaydeder yani değiştirir
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BankCartID,PersonID,BankCartName")] BankCartType bankCartType)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bankCartType).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PersonID = new SelectList(db.Persons, "PersonID", "Name", bankCartType.PersonID);
            return View(bankCartType);
        }

        // GET: BankCartTypes/Delete/5
        // id si belli olan veriyi View/BankCartTypes/Delete ekranına gösterir ve silip silmeyeceğini sorar
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BankCartType bankCartType = db.BankCartType.Find(id);
            if (bankCartType == null)
            {
                return HttpNotFound();
            }
            return View(bankCartType);
        }

        // POST: BankCartTypes/Delete/5
        // View/BankCartTypes/Delete ekranında sil butonuna basılıp Post edilen bilgi id si ile Database den silinir
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BankCartType bankCartType = db.BankCartType.Find(id);
            db.BankCartType.Remove(bankCartType);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // Dispose methodu ile Database bağlantısı kesilir ve Bellekte şişmeler engellenir
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TIEB/TIEB/Controllers/CreditCartTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TIEB.MainController;
using TIEB.Models;

namespace TIEB.Controllers
{
    // Ana bir controller tarafından inherit edilmiştir giriş yapılınca devreye girer
    public class CreditCartTypesController : BaseController
    {
        private TIEB_BudgetDBEntities db = new TIEB_BudgetDBEntities();

        // GET: CreditCartTypes
        // CreditCartType tablosundaki verileri PersonID ye göre listeler
        public ActionResult Index()
        {
            var creditCartType = db.CreditCartType.Include(c => c.Persons);
            return View(creditCartType.ToList());
        }

        // GET: CreditCartTypes/Details/5
        // Belirtilen id değerine uygun kişinin Kredi kartı bilgilerini getirir
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CreditCartType creditCartType = db.CreditCartType.Find(id);
            if (creditCartType == null)
            {
                return HttpNotFound();
            }
            return View(creditCartType);
        }

        // GET: CreditCartTypes/Create
        public ActionResult Create()
        {
            ViewBag.PersonID = new SelectList(db.Persons, "PersonID", "Name");
            return View();
        }

        // POST: CreditCartTypes/Create
        // View/Create üzerinden Post edilen verileri alır ve Databaseye kaydeder
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CreditCartID,PersonID,CreditCartName")] CreditCartType creditCartType)
        {
            if (ModelState.IsValid)
            {
                db.CreditCartType.Add(creditCartType);
                db.SaveChanges();
                return RedirectToAction("Create"); // Veri kaydedildikten sonra tekrardan Create ekranına yönlendirir.
            }

            ViewBag.PersonID = new SelectList(db.Persons, "PersonID", "Name", creditCartType.PersonID);
            return View(creditCartType);
        }

        // GET: CreditCartTypes/Edit/5
        // Belirtilen id ile kişinin Database deki Kredi kartı bilgilerini Edit ekranındaki nesnelere doldurur
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CreditCartType creditCartType = db.CreditCartType.Find(id);
            if (creditCartType == null)
            {
                return HttpNotFound();
            }
            ViewBag.PersonID = new SelectList(db.Persons, "PersonID", "Name", creditCartType.PersonID);
            return View(creditCartType);
        }

        // POST: CreditCartTypes/Edit/5
        // View/CreditCartTypes/Crate üzerinden Post edilen bilgileri Database üzerine tekrardan kaydeder yani değiştirir
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CreditCartID,PersonID,CreditCartName")] CreditCartType creditCartType)
        {
            if (ModelState.IsValid)
            {
                db.Entry(creditCartType).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PersonID = new SelectList(db.Persons, "PersonID", "Name", creditCartType.PersonID);
            return View(creditCartType);
        }

        // GET: CreditCartTypes/Delete/5
        // id si belli olan veriyi View/CreditCartTypes/Delete ekranına gösterir ve silip silmeyeceğini sorar
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CreditCartType creditCartType = db.CreditCartType.Find(id);
            if (creditCartType == null)
            {
                return HttpNotFound();
            }
            return View(creditCartType);
        }

        // POST: CreditCartTypes/Delete/5
        // View/CreditCartTypes/Delete ekranında sil butonuna basılıp Post edilen bilgi id si ile Database den silinir
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CreditCartType creditCartType = db.CreditCartType.Find(id);
            db.CreditCartType.Remove(creditCartType);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        // Dispose methodu ile Database bağlantısı kesilir ve Bellekte şişmeler engellenir
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TIEB/TIEB/Controllers/PersonsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TIEB.Models;

namespace TIEB.Controllers
{
    public class PersonsController : Controller
    {
        private TIEB_BudgetDBEntities db = new TIEB_BudgetDBEntities();

        // GET: Persons
        public ActionResult Index()
        {
            return View();
        }
        // Persons tablosundaki verileri PersonID ye göre listeler ayrıca giriş yapılan kişinin profilini gösterir
        public ActionResult List()
        {
            var persons = db.Persons.Include(p => p.BankCartType).Include(p => p.CreditCartType).Include(p => p.Expense).Include(p => p.Income);
            return View(persons.ToList());
        }

        // GET: Persons/Details/5
        // Belirtilen id değerine uygun kişinin Banka bilgilerini getirir
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Persons persons = db.Persons.Find(id);
            if (persons == null)
            {
                return HttpNotFound();
            }
            return View(persons);
        }

        // GET: Persons/Create
        public ActionResult Create()
        {
            ViewBag.PersonID = new SelectList(db.BankCartType, "BankCartID", "BankCartName");
            ViewBag.PersonID = new SelectList(db.CreditCartType, "CreditCartID", "CreditCartName");
            ViewBag.PersonID = new SelectList(db.Expense, "ExpenseID", "ExpenseID");
            ViewBag.PersonID = new SelectList(db.Income, "IncomeID", "IncomeID");
            return View();
        }

        // POST: Persons/Create
        // View/Persons/Create üzerinden Post edilen verileri alır ve Databaseye kaydeder
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PersonID,Name,SurName,UserName,Password,Email,Gender,BrithDate")] Persons persons)
        {
            if (ModelState.IsValid)
            {
                foreach (var item in db.Persons)
                {
                    if (persons.UserName == item.UserName) // Kişi eklerken Kullanıcı adı eğer Database de mevcutsa hata verir 
                    {
                        ViewBag.HATA = "Bu Kullanıcı Adı Daha Önceden Alınmış";
                        return View("Create");
                    }
                    if (persons.Email == item.Email) // Kişi eklerken mail adresi eğer Database de mevcutsa hata verir
                    {
                        ViewBag.HATA = "Bu Mail Adresi Daha Önceden Alınmış";
                        return View("Create");
                    }
                }
                db.Persons.Add(persons);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PersonID = new SelectList(db.BankCartType, "BankCartID", "BankCartName", persons.PersonID);
            ViewBag.PersonID = new SelectList(db.CreditCartType, "CreditCartID", "CreditCartName", persons.PersonID);
            ViewBag.PersonID = new SelectList(db.Expense, "ExpenseID", "ExpenseID", persons.PersonID);
            ViewBag.PersonID = new SelectList(db.Income, "IncomeID", "IncomeID", persons.PersonID);
            return View(persons);
        }

        // GET: Persons/Edit/5
        // Belirtilen id ile kişinin Database deki Banka bilgilerini Edit ekranındaki nesnelere doldurur
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Persons persons = db.Persons.Find(id);
            if (persons == null)
            {
                return HttpNotFound();
            }
            ViewBag.PersonID = new SelectList(db.BankCartType, "BankCartID", "BankCartName", persons.PersonID);
            ViewBag.PersonID = new SelectList(db.CreditCartType, "CreditCartID", "CreditCartName", persons.PersonID);
            ViewBag.PersonID = new SelectList(db.Expense, "ExpenseID", "ExpenseID", persons.PersonID);
            ViewBag.PersonID = new SelectList(db.Income, "IncomeID", "IncomeID", persons.PersonID);
            return View(persons);
        }

        // POST: Persons/Edit/5
        // View/Persons/Edit üzerinden Post edilen bilgileri Database üzerine tekrardan kaydeder yani değiştirir
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PersonID,Name,SurName,UserName,Password,Email,Gender,BrithDate")] Persons persons)
        {
            if (ModelState.IsValid)
            {
                db.Entry(persons).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PersonID = new SelectList(db.BankCartType, "BankCartID", "BankCartName", persons.PersonID);
            ViewBag.PersonID = new SelectList(db.CreditCartType, "CreditCartID", "CreditCartName", persons.PersonID);
            ViewBag.PersonID = new SelectList(db.Expense, "ExpenseID", "ExpenseID", persons.PersonID);
            ViewBag.PersonID = new SelectList(db.Income, "IncomeID", "IncomeID", persons.PersonID);
            return View(persons);
        }

        // GET: Persons/Delete/5
        // id si belli olan veriyi View/BankCartTypes/Delete ekranına gösterir ve silip silmeyeceğini sorar
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Persons persons = db.Persons.Find(id);
            if (persons == null)
            {
                return HttpNotFound();
            }
            return View(persons);
        }

        // POST: Persons/Delete/5
        // View/Persons/Delete ekranında sil butonuna basılıp Post edilen bilgi id si ile Database den silinir
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Persons persons = db.Persons.Find(id);
            db.Persons.Remove(persons);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // Dispose methodu ile Database bağlantısı kesilir ve Bellekte şişmeler engellenir
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        


    }
}

TIEB/TIEB/Views/Persons/Create.cshtml
@model TIEB.Models.Persons
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Kayıt Olma Sayfası</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SurName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SurName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SurName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                <p style="color:red">@ViewBag.HATA</p>
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

       <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Gender", new List<SelectListItem>
                {
                    new SelectListItem{ Text="Erkek", Value="Erkek"},
                    new SelectListItem{ Text="Kadın", Value="Kadın"}
                }, "--- Seçiniz ---", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>
        

        <div class="form-group">
            @Html.LabelFor(model => model.BrithDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BrithDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BrithDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kayıt Ol" class="btn btn-default" />
            </div>
        </div>
    </div>
}



@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")
}

TIEB/TIEB/Views/Persons/Delete.cshtml
@model TIEB.Models.Persons

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Silme Sayfası</h2>

<h3>Bu Kaydı Silmek İstediğinizden Emin Misiniz?</h3>
<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SurName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SurName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BrithDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BrithDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Sil" class="btn btn-default" /> |
            @Html.ActionLink("Profilime Geri Dön", "List")
        </div>
    }
</div>

TIEB/TIEB/Views/Persons/Details.cshtml
@model TIEB.Models.Persons

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Liste Detayı</h2>

<div>
    <h4>Persons</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SurName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SurName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BrithDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BrithDate)
        </dd>

        

    </dl>
</div>
<p>
    @Html.ActionLink("Düzenle", "Edit", new {  id = Model.PersonID }) |
    @Html.ActionLink("Profilime Geri Dön", "List")
</p>

TIEB/TIEB/Views/Persons/Edit.cshtml
@model TIEB.Models.Persons

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Düzenleme Sayfası</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PersonID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SurName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SurName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SurName, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.UserName)

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.Email)

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BrithDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BrithDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BrithDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Değiştir" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Profilime Geri Dön", "List")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TIEB/TIEB/Views/Persons/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

TIEB/TIEB/Views/Persons/List.cshtml
@model IEnumerable<TIEB.Models.Persons>
@using TIEB.Models;

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Profilim</h2>
<p>
    @Html.ActionLink("Banka Ekle", "Create","BankCartTypes")
</p>
<p>
    @Html.ActionLink("Credi Kartı Ekle", "Create","CreditCartTypes")
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SurName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Password)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BrithDate)
        </th>
        
        <th></th>
    </tr>
    @{ 
        var name = Session["UserName"] as Persons;
        if (name == null){return;}
    }
    
@foreach (var item in Model.Where(x => x.PersonID == name.PersonID)) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SurName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BrithDate)
            </td>


            <td>
                @Html.ActionLink("Düzenle", "Edit", new {  id=item.PersonID }) |
                @Html.ActionLink("Detay", "Details", new { id=item.PersonID }) |
                @Html.ActionLink("Sil", "Delete", new {  id=item.PersonID })
            </td>
        </tr>
    }
 
    
</table>