TIEB/TIEB/Controllers/ExpensesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TIEB.MainController;
using TIEB.Models;
using PagedList;


namespace TIEB.Controllers
{
    // Ana bir controller tarafından inherit edilmiştir giriş yapılınca devreye girer
    public class ExpensesController : BaseController
    {
        private TIEB_BudgetDBEntities db = new TIEB_BudgetDBEntities();
        public static int InstallmentID; // Taksit bilgisinin tutulacağı değişken


        //Expenses/Index Gelirlerin listelendiği sayfadır Search ve Sort işlemlerini de bu Method yapar.
        public ActionResult Index(string SearchString1, string SearchString2, string SearchString3, string SearchString4,
            string date1, string date2, string amount1, string amount2, string Sorting_Order, string sortOrder, string SearchString5,
            string currentFilter, string currentFilter1, string currentFilter2, int? page,string value)
        {
            ViewBag.SortingPaymentType = String.IsNullOrEmpty(Sorting_Order) ? "PaymentType" : "";
            ViewBag.SortingAmount = String.IsNullOrEmpty(Sorting_Order) ? "Amount" : "";
            ViewBag.SortingDate = String.IsNullOrEmpty(Sorting_Order) ? "Date" : "";
            ViewBag.SortingBank = String.IsNullOrEmpty(Sorting_Order) ? "Bank" : "";
            ViewBag.SortingCredit = String.IsNullOrEmpty(Sorting_Order) ? "Credit" : "";
            ViewBag.SortingExpenseName = String.IsNullOrEmpty(Sorting_Order) ? "ExpenseName" : "";
            ViewBag.SortingPaymentInfo = String.IsNullOrEmpty(Sorting_Order) ? "PaymentInfo" : "";
            ViewBag.SortingExplanation = String.IsNullOrEmpty(Sorting_Order) ? "Explanation" : "";
            ViewBag.SortingPaid = String.IsNullOrEmpty(Sorting_Order) ? "Paid" : "";
            ViewBag.SortingNotPaid = String.IsNullOrEmpty(Sorting_Order) ? "NotPaid" : "";

            var name = Session["UserName"] as Persons;
            if (name == null) { return View(); }

            if (Sorting_Order == null)
                Sorting_Order = sortOrder;
            ViewBag.CurrentSort = Sorting_Order;
            

            int pageSize = 10;
            int pageNumber = (page ?? 1);

            if (SearchString1 != null || SearchString2 != null || SearchString3 != null || SearchString4 != null ||
                date1 != null || date2 != null || amount1 != null || amount2 != null)
            {
                // Search değerleri null değilseler page değişkenine 1 atanır ve geri kalan search değerleri TempData da tutulur
                page = 1;
                TempData["temp1"] = SearchString1;
                TempData.Keep();
                TempData["temp2"] = SearchString2;
                TempData.Keep();
                TempData["temp3"] = SearchString3;
                TempData.Keep();
                TempData["temp4"] = SearchString4;
                TempData.Keep();
                TempData["temp5"] = date1;
                TempData.Keep();
                TempData["temp6"] = date2;
                TempData.Keep();
                TempData["temp7"] = amount1;
                TempData.Keep();
                TempData["temp8"] = amount2;
                TempData.Keep();
                TempData["temp9"] = SearchString5;
            }
            else
            {
                // Search değerleri null ise TempDataların içinde bulunan değerler geçici templere aktarılır
                string temp1 = "", temp2 = "", temp3 = "", temp4 = "";
                string temp5 = "", temp6 = "", temp7 = "", temp8 = "", temp9 = "";
                
                
                temp1 = Convert.ToString( TempData["temp1"]);
                TempData.Keep();
                temp2 = Convert.ToString(TempData["temp2"]);
                TempData.Keep();
                temp3 = Convert.ToString(TempData["temp3"]);
                TempData.Keep();
                temp4 = Convert.ToString(TempData["temp4"]);
                TempData.Keep();
                temp5 = Convert.ToString(TempData["temp5"]);
                TempData.Keep();
                temp6 = Convert.ToString(TempData["temp6"]);
                TempData.Keep();
                temp7 = Convert.ToString(TempData["temp7"]);
                TempData.Keep();
                temp8 = Convert.ToString(TempData["temp8"]);
                TempData.Keep();
                temp9 = Convert.ToString(TempData["temp9"]);
                TempData.Keep();

                // Templerin içi kontrol edilir ve boş olmayan değer varsa currenFilter e 
                // kaydedilen değer Search değerlerinden birine aktarılır
                if (temp1 != "")
                    SearchString1 = currentFilter;
                else if (temp2 != "")
                    SearchString2 = currentFilter;
                else if (temp3 != "")
                    SearchString3 = currentFilter;
                else if (temp4 != "")
                    SearchString4 = currentFilter;
                else if (temp9 != "")
                    SearchString5 = currentFilter;

                if (temp5 != "")
                    date1 = currentFilter1;
                if (temp6 != "")
                    date2 = currentFilter2;
                if (temp7 != "")
                    amount1 = currentFilter1;
                if (temp8 != "")
                    amount2 = currentFilter2;
                

            }


            // Expense Tablosundaki değerler expense değişkenine aktarılır
            var expense = from exp in db.Expense select exp;

            // Sorting_Order değişkenlerine göre sıralama işlemleri switch case default yapısıyla gerçekleşir
            switch (Sorting_Order)
            {
                case "PaymentType":
                    expense = expense.OrderBy(x => x.PaymentType).Where(x => x.PersonID == name.PersonID);
                    break;
                case "Amount":
                    expense = expense.OrderBy(x => x.Amount).Where(x => x.PersonID == name.PersonID);
                    break;
                case "Date":
                    expense = expense.OrderBy(x => x.Date).Where(x=> x.PersonID == name.PersonID);
                    break;
                case "PaymentInfo":
                    expense = expense.OrderBy(x => x.PaymentInfo).Where(x=>x.PaymentInfo != null && x.PersonID == name.PersonID);
                    break;
                case "Bank":
                    expense = (from e in db.Expense   // İlişkili tablolar olduğundan join kullanılır. BankID ve BankCartID değerine göre
                               join et in db.BankCartType on e.BankID equals et.BankCartID
                               where e.PersonID == name.PersonID
                               orderby et.BankCartName
                               select e);
                    break;
                case "Credit":
                    expense = (from e in db.Expense  // İlişkili tablolar olduğundan join kullanılır. CreditID ve CreditCartID değerine göre
                               join et in db.CreditCartType on e.CreditID equals et.CreditCartID
                               where e.PersonID == name.PersonID
                               orderby et.CreditCartName
                               select e);
                    break;
                case "ExpenseName":
                    expense = (from e in db.Expense // İlişkili tablolar olduğundan join kullanılır. ExpenseType ve ExpenseTypeID değerine göre
                               join et in db.ExpenseType on e.ExpenseType equals et.ExpenseTypeID
                               where e.PersonID == name.PersonID
                               orderby et.ExpenseName
                               select e);
                    break;
                case "Explanation":
                    expense = expense.OrderBy(e => e.Explanation).Where(x=>x.Explanation != null && x.PersonID == name.PersonID);
                    break;
                case "Paid":
                    expense = expense.OrderBy(e => e.ExpenseID).Where(x => x.PaymentInfo.Contains("Ödendi") && x.PersonID == name.PersonID);
                    break;
                case "NotPaid":
                    expense = expense.OrderBy(e => e.ExpenseID).Where(x => x.PaymentInfo.Contains("Ödenmedi") && x.PersonID == name.PersonID);
                    break;
                default:
                    expense = expense.OrderBy(x => x.ExpenseID).Where(x=>x.PersonID==name.PersonID);
                    break;

            }

            // String tipindeki Search değerlerinin boş olup olmadığı kontrol edilir ve Search değerleri içindeki 
            // değerler belirli tablolar içindek filtreleme işlemi yapar
            if (!String.IsNullOrEmpty(SearchString1))
            {
                ViewBag.CurrentFilter = SearchString1;
                expense = (from e in db.Expense
                           join et in db.ExpenseType on e.ExpenseType equals et.ExpenseTypeID
                                where et.ExpenseName.Contains(SearchString1) && e.PersonID == name.PersonID
                           orderby e.ExpenseID
                                select e);
            }
            else if (!String.IsNullOrEmpty(SearchString2))
            {
                ViewBag.CurrentFilter = SearchString2;
                expense = expense.Where(x => x.PaymentType.Contains(SearchString2) 
                && x.PersonID == name.PersonID).OrderBy(x => x.ExpenseID);
            }
            else if (!String.IsNullOrEmpty(SearchString3))
            {
                ViewBag.CurrentFilter = SearchString3;
                expense = (from e in db.Expense
                                join b in db.BankCartType on e.BankID equals b.BankCartID
                                where b.BankCartName.Contains(SearchString3) && e.PersonID == name.PersonID
                           orderby e.ExpenseID

TIEB/TIEB/Views/Expenses/Create.cshtml
@model TIEB.Models.Expense
@using TIEB.Models;
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<head>
    @*div bloklarını yan yana koymak için css*@
    <style type="text/css">
        .column {
            float:left;
            width:560px; 
        }
    </style>
</head>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

   

    <div class="form-horizontal column">
        <h4>Gider Ekleme Sayfası</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @{
            var name = Session["UserName"] as Persons;
            if (name == null) { return; } @*Kullanıcı girşi ile Sessiona kaydedilen kullanıcı adı kontrolü boş mu dolu mu?*@
        }
        <div class="form-group" hidden>
            @Html.LabelFor(model => model.PersonID, "PersonID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("PersonID", name.PersonID, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PersonID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpenseType, "Harcama Türü", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ExpenseType", null, "--- Seçiniz ---", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ExpenseType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PaymentType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PaymentType", new List<SelectListItem>
                {
                    @*PaymentType DropDownListinin içinde seçilecek değerler*@
                    new SelectListItem{ Text="Nakit", Value="Nakit"},
                    new SelectListItem{ Text="Kart", Value="Kart"},
                    new SelectListItem{ Text="Banka", Value="Banka"}
                }, "--- Seçiniz ---", new { @class = "form-control" })
                @Html.ValidationMessage("PaymentType", "", new { @class = "text-danger" })
            </div>
        </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                </div>
            </div>
            
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Kaydet" class="btn btn-default" />
                </div>
            </div>
            <div>
                @Html.ActionLink("Listeye Geri Dön", "Index")
            </div>
        </div>
        <div class="form-horizontal column" id="form-ExpTextBox" hidden>
            <h4>Listede Olmayan Gelir Türü Giriniz</h4>
            <hr />
            <div class="col-md-10">
                @Html.EditorFor(model => model.Explanation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Explanation, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-horizontal column" id="form-payment" hidden>
            <h4>Ödeme Türü</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group" id="bank-group" hidden>
                @Html.LabelFor(model => model.BankID, "Banka Adı", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("BankID", null, "--- Seçiniz ---", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.BankID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group" id="credit-group" hidden>
                @Html.LabelFor(model => model.CreditID, "Kredi Kartı Adı", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("CreditID", null, "--- Seçiniz ---", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CreditID, "", new { @class = "text-danger" })
                </div>
                <br /><br /><br />
                @Html.Label("installment", "Taksit", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("installment",null, "--- Seçiniz ---", new { @class = "form-control" })
                    @Html.ValidationMessage("installment", "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

}




@section scripts
{
    <script type="text/javascript">
        $(document).ready(function () {
            $("#ExpenseType").change(function () { // ExpenseType nesnesi seçildiğinde 
                var id = $(this).val();
                $.ajax({
                    url: '/Expenses/ExpenseTypeOther',
                    type: 'POST',
                    dataType: 'json',
                    data: { 'id': id }, // ExpenseTypeOther Methodunun parametresine id değeri Json olarak gönderilir
                    success: function (data) {
                         // Json olarak geri dönen değer başarılıysa if yapısıyla kontrol edilir
                        // ExpTextBox ın görünüp görünmeyeceği belirlenir
                        if (data.Message == "AppearTextBox") {
                            $("#form-ExpTextBox").show();
                        }
                        else {
                            $("#form-ExpTextBox").hide();
                        }

                    }
                });
            });
            $("#PaymentType").change(function () { // PaymentType nesnesi seçildiğinde
                var value = $(this).val();

                $.ajax({
                    url: '/Expenses/PaymentType',
                    type: 'POST',
                    dataType: 'json',
                    data: { 'value': value }, // PaymentType Methodunun parametresine value değeri Json olarak gönderilir
                    success: function (data) {
                        // Json olarak geri dönen değer başarılıysa if yapısıyla kontrol edilir
                        // Hangi nesnelerin görünüp görünmeyeceği belirlenir
                        if (data.Message == "AppearCash") {
                            $("#form-payment").hide();
                        }
                        else if (data.Message == "AppearCard") {
                            $("#form-payment").show();
                            $("#bank-group").hide();
                            $("#credit-group").show();
                        }
                        else if (data.Message == "AppearBank") {
                            $("#form-payment").show();
                            $("#bank-group").show();
                            $("#credit-group").hide();
                        }
                    }

                });

            });
            $("#installment").change(function () { // installment nesnesi seçildiğinde
                var id = $(this).val();
                $.ajax({
                    url: '/Expenses/CreateInstallment',
                    type: 'POST',
                    dataType: 'json',
                    data: { 'installment': id }, // CreateInstallment Methodunun parametresine id değeri Json olarak gönderilir
                    success: function (data) {
                        
                    }
                });
            });
        });
    </script>
}

TIEB/TIEB/Views/Expenses/Index.cshtml
@*@model IEnumerable<TIEB.Models.Expense>*@
@model PagedList.IPagedList< TIEB.Models.Expense>
@using TIEB.Models;
@using PagedList.Mvc;

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>GİDERLERİM</h2>
<head>
    <style type="text/css">
        .column {
            float: left;
            width: 250px;
        }
    </style>
</head>

<p>
    @Html.ActionLink("Gider Ekle", "Create")
</p>

<div class="form-group pull-right">
    
    @Html.Label("Arama Kriteri", htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.DropDownList("searchType", new List<SelectListItem>
                {
                    
                    new SelectListItem{ Text="Harcama Türüne Göre Arama", Value="ExpenseTypeSearch"},
                    new SelectListItem{ Text="Ödeme Tipine Göre Arama", Value="PaymentSearch"},
                    new SelectListItem{ Text="Banka Adına Göre Arama", Value="BankSearch"},
                    new SelectListItem{ Text="Credi Kartına Göre Arama", Value="CreditSearch"},
                    new SelectListItem{ Text="Miktara Göre Arama", Value="AmountSearch"},
                    new SelectListItem{ Text="Tarihe Göre Arama", Value="DateSearch"},
                    new SelectListItem{ Text="Diğer Harcama Türüne Göre Arama", Value="OtherExpenseTypeSearch"}

                }, "--- Seçiniz ---", new { @class = "form-control" })
        @Html.ValidationMessage("searchType", "", new { @class = "text-danger" })
    </div>
</div>
<br /><br /><br />
<p class="pull-left column">
    @Html.ActionLink("Listeyi Yenile", "Index")
</p>
<p class="column">
    Toplam : @ViewBag.TOTAL
</p>
@using (Html.BeginForm())
{

    <div class="pull-right" id="form-search1" hidden>
        <b>Harcama Türüne Göre Arama Yap:</b> 
        @Html.TextBox("SearchString1",ViewBag.CurrentFilter as string)
        <input type="submit" value="Arama Yap" id="search"/>
    </div>
    <div class="pull-right" id="form-search2" hidden>
        <b>Ödeme Tipine Göre Arama Yap:</b> 
        @Html.TextBox("SearchString2", ViewBag.CurrentFilter as string)
        <input type="submit" value="Arama Yap" id="search" />
    </div>
    <div class="pull-right" id="form-search3" hidden>
        <b>Banka Adına Göre Arama Yap:</b> 
        @Html.TextBox("SearchString3", ViewBag.CurrentFilter as string)
        <input type="submit" value="Arama Yap" id="search" />
    </div>
    <div class="pull-right" id="form-search4" hidden>
        <b>Credi Kartına Göre Arama Yap:</b> 
        @Html.TextBox("SearchString4", ViewBag.CurrentFilter as string)
        <input type="submit" value="Arama Yap" id="search" />
    </div>
    <div class="pull-right" id="form-search5" hidden>
        <b>Diğer Harcama Türüne Göre Arama Yap:</b>
        @Html.TextBox("SearchString5", ViewBag.CurrentFilter as string)
        <input type="submit" value="Arama Yap" id="search" />
    </div>
    <div class="pull-right" id="form-between-date" hidden>
        <b>İki Tarih Arası Arama:</b> 
        @Html.TextBox("date1", ViewBag.CurrentFilter1 as string)
        @Html.TextBox("date2", ViewBag.CurrentFilter2 as string)
        <input type="submit" value="Arama Yap" id="search" />
    </div>
    <div class="pull-right" id="form-between-amount" hidden>
        <b>Miktarlar Arası Arama:</b>
        @Html.TextBox("amount1", ViewBag.CurrentFilter1 as string)
        @Html.TextBox("amount2", ViewBag.CurrentFilter2 as string)
        <input type="submit" value="Arama Yap" id="search" />
    </div>
}
<br /><br /><br />
@using (Html.BeginForm("Index", "Expenses", FormMethod.Post))
{
    <table class="table" style="text-align:center" >
        <tr >
            <th style="text-align:center">
                @Html.ActionLink("Harcama Türü", "Index", new { Sorting_Order = ViewBag.SortingExpenseName , currentFilter=ViewBag.CurrentFilter})
            </th>

            <th style="text-align:center">
                @Html.ActionLink("Ödeme Tipi", "Index", new { Sorting_Order = ViewBag.SortingPaymentType, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("Banka", "Index", new { Sorting_Order = ViewBag.SortingBank, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th style="text-align:center">
                @Html.ActionLink("Credi Kart", "Index", new { Sorting_Order = ViewBag.SortingCredit, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th style="color:steelblue; text-align:center">
                @Html.DisplayName("Taksit Bilgileri")
            </th>
            <th style="text-align:center">
                @Html.ActionLink("Miktar", "Index",  new { Sorting_Order = ViewBag.SortingAmount, currentFilter1 = ViewBag.CurrentFilter1 , currentFilter2 = ViewBag.CurrentFilter2 })
            </th>
            <th style="text-align:center">
                @Html.ActionLink("Tarih", "Index",  new { Sorting_Order = ViewBag.SortingDate, currentFilter1 = ViewBag.CurrentFilter1, currentFilter2 = ViewBag.CurrentFilter2 })
            </th>
            <th style="text-align:center">
                <div>
                    @Html.ActionLink("Ödeme Bilgisi", "Index", new { Sorting_Order = ViewBag.SortingPaymentInfo, currentFilter = ViewBag.CurrentFilter })
                </div>
                <div>
                    @Html.ActionLink("Ödendi", "Index", new { Sorting_Order = ViewBag.SortingPaid, currentFilter = ViewBag.CurrentFilter }) | 
                    @Html.ActionLink("Ödenmedi", "Index", new { Sorting_Order = ViewBag.SortingNotPaid, currentFilter = ViewBag.CurrentFilter })
                </div>
            </th>
            <th style="text-align:center">
                @Html.ActionLink("Diğer Harcama Türü", "Index", new { Sorting_Order = ViewBag.SortingExplanation, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th></th>
        </tr>
        @{
            var name = Session["UserName"] as Persons;
            if(name == null){ return; }
        }

    @foreach (var item in Model.Where(x => x.PersonID == name.PersonID))
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ExpenseType1.ExpenseName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PaymentType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BankCartType.BankCartName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreditCartType.CreditCartName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InstallmentInfo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PaymentInfo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Explanation)
            </td>
            <td>
                @Html.ActionLink("Düzenle", "Edit", new { id=item.ExpenseID }) |
                @Html.ActionLink("Detay", "Details", new { id=item.ExpenseID }) |
                @Html.ActionLink("Sil", "Delete", new { id=item.ExpenseID })
            </td>
        </tr>
    }

    </table>
}
<br /><br />
@(Html.Raw(ViewBag.HtmlStr)) sonuç
<br />
Sayfa @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page,sortOrder=ViewBag.CurrentSort, currentFilter=ViewBag.CurrentFilter, currentFilter1 = ViewBag.CurrentFilter1, currentFilter2 = ViewBag.CurrentFilter2 }))



@section scripts
{
    <script type="text/javascript">
        $(document).ready(function () {
            
            $("#searchType").change(function () {
                    var value = $(this).val();
                    $.ajax({
                        url: '/Expenses/SearchType',
                        type: 'POST',
                        dataType: 'json',
                        data: { 'value': value },
                        success: function (data) {
                            
                            if (data.Message == "AppearPayment") {
                                $("#form-between-amount").hide();
                                $("#form-between-date").hide();
                                $("#form-search1").hide();
                                $("#form-search2").show();
                                $("#form-search3").hide();
                                $("#form-search4").hide();
                                $("#form-search5").hide();
                            }
                            else if (data.Message == "AppearAmount") {
                                $("#form-between-amount").show();
                                $("#form-between-date").hide();
                                $("#form-search1").hide();
                                $("#form-search2").hide();
                                $("#form-search3").hide();
                                $("#form-search4").hide();
                                $("#form-search5").hide();
                            }
                            else if (data.Message == "AppearDate") {
                                $("#form-between-amount").hide();
                                $("#form-between-date").show();
                                $("#form-search1").hide();
                                $("#form-search2").hide();
                                $("#form-search3").hide();
                                $("#form-search4").hide();
                                $("#form-search5").hide();
                            }
                            else if (data.Message == "AppearExpenseT") {
                                $("#form-between-amount").hide();
                                $("#form-between-date").hide();
                                $("#form-search1").show();
                                $("#form-search2").hide();
                                $("#form-search3").hide();
                                $("#form-search4").hide();
                                $("#form-search5").hide();
                            }
                            else if (data.Message == "AppearBank") {
                                $("#form-between-amount").hide();
                                $("#form-between-date").hide();
                                $("#form-search1").hide();
                                $("#form-search2").hide();
                                $("#form-search3").show();
                                $("#form-search4").hide();
                                $("#form-search5").hide();
                            }
                            else if (data.Message == "AppearCredit") {
                                $("#form-between-amount").hide();
                                $("#form-between-date").hide();
                                $("#form-search1").hide();
                                $("#form-search2").hide();
                                $("#form-search3").hide();
                                $("#form-search4").show();
                                $("#form-search5").hide();
                            }
                            else if (data.Message == "AppearOtherExpenseT") {
                                $("#form-between-amount").hide();
                                $("#form-between-date").hide();
                                $("#form-search1").hide();
                                $("#form-search2").hide();
                                $("#form-search3").hide();
                                $("#form-search4").hide();
                                $("#form-search5").show();
                            }
                        }

                    });
                });
            });
    </script>
}